name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm" # Re-enabled cache for pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # Using the official pnpm setup action
        with:
          version: 8 # Specify pnpm version, or omit for latest stable
          run_install: false # We'll run pnpm install in a separate step

      - name: Install dependencies
        run: pnpm install

      - name: Run linting
        run: pnpm lint

      - name: Run type checking
        run: pnpm type-check

      - name: Run unit tests
        run: pnpm test
        env:
          MONGODB_URI: mongodb://localhost:27017/vitamend-test
          NEXTAUTH_SECRET: test-secret # Consider using GitHub Secrets for production

      - name: Build application
        run: pnpm build && pnpm export

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install serve and start-server-and-test
        # Ensure 'serve' and 'start-server-and-test' are in your package.json devDependencies
        run: pnpm install serve start-server-and-test # Install if not already in package.json

      - name: Run E2E tests
        # Use start-server-and-test to ensure the app is running before Playwright tests
        run: start-server-and-test "serve out -l 3000" http://localhost:3000 "npx playwright test"
        env:
          MONGODB_URI: mongodb://localhost:27017/vitamend-test
          NEXTAUTH_SECRET: test-secret # Consider using GitHub Secrets for production

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out # This path should match the output of 'pnpm export'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
